spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: "jdbc:h2:mem:NisumDB"
    username: "root"
    password: "root"
    driverClassName: "org.h2.Driver"
  jpa:
    defer-datasource-initialization: true
    databasePlatform: "org.hibernate.dialect.H2Dialect"